name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0,4,12 * * *'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        base_url: ['', 'https://fast.huacai.one']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Run your tests
      run: pytest --base-url=${{ matrix.base_url }} --reruns 3 --reruns-delay 2
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-traces_and_results
        path: |
          allure-results/
          *trace.zip
